export const GET_MOVIES = "GET_MOVIES";
export const FETCH_SEARCH_MOVIES = "FETCH_SEARCH_MOVIES";
export const FETCH_BY_GENRES = "FETCH_BY_GENRES";

export const FETCH_GENRES = "FETCH_GENRES";
export const GET_GENRES = "GET_GENRES";
export const FETCH_AUTOCOMPLETE_MOVIES = "FETCH_AUTOCOMPLETE_MOVIES";
export const GET_AUTOCOMPLETE_MOVIES = "GET_AUTOCOMPLETE_MOVIES";
